use_frameworks!

platform :ios, '9.0'

target 'DYVideoCamera_Example' do
  pod 'DYVideoCamera', :path => '../'
# TODO： 滑动播放组建
  pod 'DYVideoListKit'
  pod 'GPUImage', :git => 'https://github.com/doubleYang1020/GPUImage'
end
